configuration:
  registries:
    - server: ${ACR_NAME}.azurecr.io
      identity: system

template:
  containers:
    - name: data-processor
      image: ${FULL_IMAGE_NAME}

      resources:
        cpu: 0.5
        memory: 1Gi

      env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod

  scale:
    minReplicas: 0
    maxReplicas: 1
    rules:
      - name: kafka-scale
        custom:
          type: kafka
          metadata:
            topic: vehicle-telemetry
            lagThreshold: "10"
