name: data-processor
type: Microsoft.Web/containerApps
location: ${LOCATION}

properties:
  managedEnvironmentId: /subscriptions/${SUB_ID}/resourceGroups/${RESOURCE_GROUP}/providers/Microsoft.Web/managedEnvironments/${ENVIRONMENT_NAME}

  configuration:
    registries:
      - server: ${ACR_NAME}.azurecr.io
        identity: system

  template:
    containers:
      - name: data-processor
        image: ${ACR_NAME}.azurecr.io/emergencywatch/data-processor:latest

        resources:
          cpu: 0.25
          memory: 0.5Gi

        env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod

        probes:
          - type: Readiness
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          - type: Liveness
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

    scale:
      minReplicas: 1
      maxReplicas: 1
      rules:
        - name: kafka-scale
          custom:
            type: kafka
            metadata:
              topic: vehicle-telemetry
              lagThreshold: "10"
