name: data-processor

managedEnvironmentId: /subscriptions/${SUB_ID}/resourceGroups/${RESOURCE_GROUP}/providers/Microsoft.App/managedEnvironments/${ENVIRONMENT_NAME}

properties:
  configuration:
    activeRevisionsMode: Single

    registries:
      - server: ${ACR_NAME}.azurecr.io
        identity: system

  template:
    containers:
      - name: data-processor
        image: ${FULL_IMAGE_NAME}

        resources:
          cpu: 0.5
          memory: 1Gi

        env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod

    scale:
      minReplicas: 0
      maxReplicas: 1
      rules:
        - name: eventhub-scale
          custom:
            type: azure-eventhub
            metadata:
              eventHubName: vehicle-telemetry
              consumerGroup: $Default
              unprocessedEventThreshold: "10"
            auth:
              - triggerParameter: connection
                secretRef: eventhub-connection
