name: notification-service
type: Microsoft.App/containerApps
location: ${LOCATION}

properties:
  managedEnvironmentId: /subscriptions/${SUB_ID}/resourceGroups/${RESOURCE_GROUP}/providers/Microsoft.App/managedEnvironments/${ENVIRONMENT_NAME}

  configuration:
    ingress:
      external: true
      targetPort: 8083
      transport: auto
      traffic:
        - latestRevision: true
          weight: 100

    registries:
      - server: ${ACR_NAME}.azurecr.io
        identity: system

  template:
    containers:
      - name: notification-service
        image: ${FULL_IMAGE_NAME}

        resources:
          cpu: 0.5
          memory: 1Gi

        env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod

        probes:
          - type: Startup
            httpGet:
              path: /actuator/health/liveness
              port: 8083
            initialDelaySeconds: 5  # Start checking almost immediately
            periodSeconds: 10       # checks every 10 seconds
            failureThreshold: 24    # for a total of 240 seconds (4 minutes)

          - type: Readiness
            httpGet:
              path: /actuator/health/readiness
              port: 8083
            # initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          - type: Liveness
            httpGet:
              path: /actuator/health/liveness
              port: 8083
            # initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

    scale:
      minReplicas: 0
      maxReplicas: 1
      rules:
        - name: http-scale
          http:
            metadata:
              concurrentRequests: "50"
