configuration:
  ingress:
    external: true
    targetPort: 8083
    transport: auto
    traffic:
      - latestRevision: true
        weight: 100

  registries:
    - server: ${ACR_NAME}.azurecr.io
      identity: system

template:
  containers:
    - name: notification-service
      image: ${FULL_IMAGE_NAME}

      resources:
        cpu: 0.5
        memory: 1Gi

      env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod

      probes:
        - type: Startup
          httpGet:
            path: /actuator/health/liveness
            port: 8083
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 24

        - type: Readiness
          httpGet:
            path: /actuator/health/readiness
            port: 8083
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3

        - type: Liveness
          httpGet:
            path: /actuator/health/liveness
            port: 8083
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3

  scale:
    minReplicas: 0
    maxReplicas: 1
    rules:
      - name: http-scale
        http:
          metadata:
            concurrentRequests: "50"
