name: emergencywatch-notification-service
type: Microsoft.Web/containerApps
location: ${LOCATION}

properties:
  managedEnvironmentId: /subscriptions/${SUB_ID}/resourceGroups/${RESOURCE_GROUP}/providers/Microsoft.Web/managedEnvironments/${ENVIRONMENT_NAME}

  configuration:
    ingress:
      external: false
      targetPort: 8083
      traffic:
        - latestRevision: true
          weight: 100

    registries:
      - server: ${ACR_NAME}.azurecr.io
        identity: system

  template:
    containers:
      - name: notification-service
        image: ${ACR_NAME}.azurecr.io/emergencywatch/notification-service:latest

        resources:
          cpu: 0.25
          memory: 0.5Gi

        env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod

        probes:
          - type: Readiness
            httpGet:
              path: /actuator/health/readiness
              port: 8083
            initialDelaySeconds: 10
            periodSeconds: 10

          - type: Liveness
            httpGet:
              path: /actuator/health/liveness
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 30

    scale:
      minReplicas: 1
      maxReplicas: 1
      rules:
        - name: http-scale
          http:
            metadata:
              concurrentRequests: "50"
