name: vehicle-simulator
type: Microsoft.Web/containerApps
location: ${LOCATION}

properties:
  managedEnvironmentId: /subscriptions/${SUB_ID}/resourceGroups/${RESOURCE_GROUP}/providers/Microsoft.Web/managedEnvironments/${ENVIRONMENT_NAME}

  configuration:
    registries:
      - server: ${ACR_NAME}.azurecr.io
        identity: system

  template:
    containers:
      - name: vehicle-simulator
        image: ${ACR_NAME}.azurecr.io/emergencywatch/vehicle-simulator:latest

        resources:
          cpu: 0.5
          memory: 1Gi

        env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod

    scale:
      minReplicas: 0
      maxReplicas: 1
