name: vehicle-simulator
type: Microsoft.App/containerApps
location: ${LOCATION}

identity:
  type: SystemAssigned

environmentId: /subscriptions/${SUB_ID}/resourceGroups/${RESOURCE_GROUP}/providers/Microsoft.App/managedEnvironments/${ENVIRONMENT_NAME}

properties:
  managedEnvironmentId: /subscriptions/${SUB_ID}/resourceGroups/${RESOURCE_GROUP}/providers/Microsoft.App/managedEnvironments/${ENVIRONMENT_NAME}

  configuration:
    activeRevisionsMode: Single

    registries:
      - server: ${ACR_NAME}.azurecr.io
        identity: system

  template:
    containers:
      - name: vehicle-simulator
        image: ${FULL_IMAGE_NAME}

        resources:
          cpu: 0.5
          memory: 1Gi

        env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod

    scale:
      minReplicas: 0
      maxReplicas: 1

