identity:
  managedEnvironmentId: /subscriptions/${SUB_ID}/resourceGroups/${RESOURCE_GROUP}/providers/Microsoft.App/managedEnvironments/${ENVIRONMENT_NAME}
  type: SystemAssigned
properties:
  managedEnvironmentId: /subscriptions/${SUB_ID}/resourceGroups/${RESOURCE_GROUP}/providers/Microsoft.App/managedEnvironments/${ENVIRONMENT_NAME}
  configuration:
    activeRevisionsMode: Single
    registries:
    - server: ${ACR_NAME}.azurecr.io
      identity: system
    secrets:
    - name: eventhub-connection-string
      keyVaultUrl: "https://emergencywatch-kv.vault.azure.net/secrets/eventhub-connection-string/bef4865e6f45499c90806824d3fcb667"
      identity: system
    - name: eventhub-sasl-config
      keyVaultUrl: "https://emergencywatch-kv.vault.azure.net/secrets/eventhub-sasl-config/0affb29645024d4c8d1f73d379d2906f"
      identity: system
  template:
    containers:
    - image: ${FULL_IMAGE_NAME}
      name: vehicle-simulator
      resources:
        cpu: 0.5
        memory: 1Gi
      env:
      - name: "SPRING_PROFILES_ACTIVE"
        value: "prod"
      # Kafka / Event hubs
      - name: "SPRING_KAFKA_BOOTSTRAP_SERVERS"
        value: "emergencywatch-eventhub.servicebus.windows.net:9093"
      # standard event hub configs
      - name: "SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL"
        value: "SASL_SSL"
      - name: "SPRING_KAFKA_PROPERTIES_SASL_MECHANISM"
        value: "PLAIN"
      - name: "AZURE_EVENTHUBS_NAMESPACE"
        value: "emergencywatch-eventhub"
      - name: "SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG"
        secretRef: eventhub-sasl-config
      - name: "AZURE_EVENTHUBS_CONNECTION_STRING"
        secretRef: eventhub-connection-string
    scale:
      minReplicas: 0
      maxReplicas: 1
      rules:
      - name: weekday-active
        custom:
          type: cron
          metadata:
            timezone: "Europe/Berlin"
            start: "55 6 * * 1-5"         # 6:55 AM Mon-Fri
            end: "0 17 * * 1-5"           # 5:00 PM Mon-Fri
            desiredReplicas: "1"
