name: vehicle-simulator
type: Microsoft.Web/containerApps
location: ${LOCATION}

properties:
  managedEnvironmentId: /subscriptions/${SUB_ID}/resourceGroups/${RESOURCE_GROUP}/providers/Microsoft.Web/managedEnvironments/${ENVIRONMENT_NAME}

  configuration:
    registries:
      - server: ${ACR_NAME}.azurecr.io
        identity: system

  template:
    containers:
      - name: vehicle-simulator
        image: ${ACR_NAME}.azurecr.io/emergencywatch/vehicle-simulator:latest

        resources:
          cpu: 0.25
          memory: 0.5Gi

        env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod

        probes:
          - type: Readiness
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10

          - type: Liveness
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30

    scale:
      minReplicas: 1
      maxReplicas: 1
